# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  
variables:
  - group: SNOWFLAKE_DEVOPS
  - name: PRIVATE_KEY_PATH
    value: ./rsa_key.p8

steps:
    - checkout: self

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.11'
        addToPath: true

    - script: |
        echo "$(SF_SVC_DEVOPS_GITLAB_PRIVATE_KEY_1_B64)" 
        chmod 0600 deploy/config/connection.toml
        echo "$(SF_SVC_DEVOPS_GITLAB_PRIVATE_KEY_1_B64)" | base64 -d > "$(PRIVATE_KEY_PATH)"
        chmod 0600 "$(PRIVATE_KEY_PATH)"
        echo "Private key path: $(PRIVATE_KEY_PATH)"
      displayName: Prepare deployment credentials
      env:
        SF_SVC_DEVOPS_GITLAB_PRIVATE_KEY_1_B64: $(SF_SVC_DEVOPS_GITLAB_PRIVATE_KEY_1_B64)

    - script: |
        python --version
        pip install --upgrade pip
        pip install schemachange
      displayName: Install pip and schemachange

    - script: |
        echo "Running Deploy"
        schemachange deploy --config-folder $(System.DefaultWorkingDirectory)/deploy/config/
      displayName: Run schemachange deployment