trigger: none  # No automatic trigger; manual only, similar to workflow_dispatch

pool:
  vmImage: ubuntu-latest

variables:
  - group: SNOWFLAKE_DEVOPS
  - name: PRIVATE_KEY_PATH
    value: ./rsa_key.p8

steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'
      addToPath: true

  - script: |
      python --version
      pip install --upgrade pip
      pip install snowflake-cli
    displayName: Install Python dependencies

  - script: |
      chmod 0600 deploy/config/connection.toml
      echo "$(SF_SVC_DEVOPS_GITLAB_PRIVATE_KEY_1_B64)" | base64 -d > "$(PRIVATE_KEY_PATH)"
      chmod 0600 "$(PRIVATE_KEY_PATH)"
    displayName: Prepare deployment credentials
    env:
      SF_SVC_DEVOPS_GITLAB_PRIVATE_KEY_1_B64: $(SF_SVC_DEVOPS_GITLAB_PRIVATE_KEY_1_B64)

  - script: |
      snow --version

      snow --config-file "deploy/config/connection.toml" \
        git fetch \
        --connection "KEY_PAIR" \
        db_governance.REPO.azdevops_repo

      snow --config-file "deploy/config/connection.toml" \
        git execute \
        --connection "KEY_PAIR" --database "db_governance" --schema "repo" \
        @azdevops_repo/branches/main/deploy/script/snowcli/* \
        -D "env_prefix='DEV'"
    displayName: Run SnowCLI deployment
