SHOW WAREHOUSES;
SHOW USERS;
SHOW ROLES;
SHOW DATABASES;
SHOW SCHEMAS IN DATABASE COLES_PURGE_TEST;
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY LIMIT 100;




SELECT * FROM COLES_PURGE_TEST.DIM.CUSTOMER;
SELECT * FROM COLES_PURGE_TEST.DIM.NATION;
show tables in database coles_purge_test;

select * from coles_purge_test.dim.part;